# RT-Thread building script for component

from building import *

Import('rtconfig')

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd]

if GetDepend('RT_USING_NVHE'):
    src = Glob('*.c') + Glob('*.cpp') + Glob('*.S')

group = DefineGroup('nvhe', src, depend = ['RT_USING_NVHE'], CPPPATH = CPPPATH)

# build for sub-directory
list = os.listdir(cwd)
objs = []

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
group = group + objs

Return('group')
